// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/jeffsvajlenko/fortissimo/server/ent/schema"
	"github.com/jeffsvajlenko/fortissimo/server/ent/song"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	songFields := schema.Song{}.Fields()
	_ = songFields
	// songDescPlayCount is the schema descriptor for play_count field.
	songDescPlayCount := songFields[23].Descriptor()
	// song.DefaultPlayCount holds the default value on creation for the play_count field.
	song.DefaultPlayCount = songDescPlayCount.Default.(uint32)
	// songDescSkippedCount is the schema descriptor for skipped_count field.
	songDescSkippedCount := songFields[24].Descriptor()
	// song.DefaultSkippedCount holds the default value on creation for the skipped_count field.
	song.DefaultSkippedCount = songDescSkippedCount.Default.(uint32)
}
