// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Song is the predicate function for song builders.
type Song func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
