// Code generated by entc, DO NOT EDIT.

package song

const (
	// Label holds the string label denoting the song type in the database.
	Label = "song"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldTitleSort holds the string denoting the title_sort field in the database.
	FieldTitleSort = "title_sort"
	// FieldArtists holds the string denoting the artists field in the database.
	FieldArtists = "artists"
	// FieldFirstArtist holds the string denoting the first_artist field in the database.
	FieldFirstArtist = "first_artist"
	// FieldFirstArtistSort holds the string denoting the first_artist_sort field in the database.
	FieldFirstArtistSort = "first_artist_sort"
	// FieldFirstAlbumArtist holds the string denoting the first_album_artist field in the database.
	FieldFirstAlbumArtist = "first_album_artist"
	// FieldFirstAlbumArtistSort holds the string denoting the first_album_artist_sort field in the database.
	FieldFirstAlbumArtistSort = "first_album_artist_sort"
	// FieldAlbumArtist holds the string denoting the album_artist field in the database.
	FieldAlbumArtist = "album_artist"
	// FieldAlbum holds the string denoting the album field in the database.
	FieldAlbum = "album"
	// FieldPublisher holds the string denoting the publisher field in the database.
	FieldPublisher = "publisher"
	// FieldFirstComposer holds the string denoting the first_composer field in the database.
	FieldFirstComposer = "first_composer"
	// FieldComposers holds the string denoting the composers field in the database.
	FieldComposers = "composers"
	// FieldConductor holds the string denoting the conductor field in the database.
	FieldConductor = "conductor"
	// FieldGenre holds the string denoting the genre field in the database.
	FieldGenre = "genre"
	// FieldGrouping holds the string denoting the grouping field in the database.
	FieldGrouping = "grouping"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldTrackNumber holds the string denoting the track_number field in the database.
	FieldTrackNumber = "track_number"
	// FieldOfTrackNumber holds the string denoting the of_track_number field in the database.
	FieldOfTrackNumber = "of_track_number"
	// FieldDiskNumber holds the string denoting the disk_number field in the database.
	FieldDiskNumber = "disk_number"
	// FieldOfDiskNumber holds the string denoting the of_disk_number field in the database.
	FieldOfDiskNumber = "of_disk_number"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldPlayCount holds the string denoting the play_count field in the database.
	FieldPlayCount = "play_count"
	// FieldSkippedCount holds the string denoting the skipped_count field in the database.
	FieldSkippedCount = "skipped_count"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldBeatsPerMinute holds the string denoting the beats_per_minute field in the database.
	FieldBeatsPerMinute = "beats_per_minute"
	// FieldCopyright holds the string denoting the copyright field in the database.
	FieldCopyright = "copyright"
	// FieldDateTagged holds the string denoting the date_tagged field in the database.
	FieldDateTagged = "date_tagged"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldFirstComposerSort holds the string denoting the first_composer_sort field in the database.
	FieldFirstComposerSort = "first_composer_sort"
	// FieldArtistsSort holds the string denoting the artists_sort field in the database.
	FieldArtistsSort = "artists_sort"
	// FieldLyrics holds the string denoting the lyrics field in the database.
	FieldLyrics = "lyrics"
	// FieldInitialKey holds the string denoting the initial_key field in the database.
	FieldInitialKey = "initial_key"
	// FieldIsrc holds the string denoting the isrc field in the database.
	FieldIsrc = "isrc"
	// FieldSubtitle holds the string denoting the subtitle field in the database.
	FieldSubtitle = "subtitle"
	// FieldMusicBrainzArtistID holds the string denoting the music_brainz_artist_id field in the database.
	FieldMusicBrainzArtistID = "music_brainz_artist_id"
	// FieldMusicBrainzDiscID holds the string denoting the music_brainz_disc_id field in the database.
	FieldMusicBrainzDiscID = "music_brainz_disc_id"
	// FieldMusicBrainzReleaseArtistID holds the string denoting the music_brainz_release_artist_id field in the database.
	FieldMusicBrainzReleaseArtistID = "music_brainz_release_artist_id"
	// FieldMusicBrainzReleaseCountry holds the string denoting the music_brainz_release_country field in the database.
	FieldMusicBrainzReleaseCountry = "music_brainz_release_country"
	// FieldMusicBrainzReleaseGroupID holds the string denoting the music_brainz_release_group_id field in the database.
	FieldMusicBrainzReleaseGroupID = "music_brainz_release_group_id"
	// FieldMusicBrainzReleaseID holds the string denoting the music_brainz_release_id field in the database.
	FieldMusicBrainzReleaseID = "music_brainz_release_id"
	// FieldMusicBrainzReleaseStatus holds the string denoting the music_brainz_release_status field in the database.
	FieldMusicBrainzReleaseStatus = "music_brainz_release_status"
	// FieldMusicBrainzReleaseType holds the string denoting the music_brainz_release_type field in the database.
	FieldMusicBrainzReleaseType = "music_brainz_release_type"
	// FieldMusicBrainzTrackID holds the string denoting the music_brainz_track_id field in the database.
	FieldMusicBrainzTrackID = "music_brainz_track_id"
	// FieldMusicIPID holds the string denoting the music_ip_id field in the database.
	FieldMusicIPID = "music_ip_id"
	// FieldRemixedBy holds the string denoting the remixed_by field in the database.
	FieldRemixedBy = "remixed_by"
	// FieldReplayGainAlbumGain holds the string denoting the replay_gain_album_gain field in the database.
	FieldReplayGainAlbumGain = "replay_gain_album_gain"
	// FieldReplayGainAlbumPeak holds the string denoting the replay_gain_album_peak field in the database.
	FieldReplayGainAlbumPeak = "replay_gain_album_peak"
	// FieldReplayGainTrackGain holds the string denoting the replay_gain_track_gain field in the database.
	FieldReplayGainTrackGain = "replay_gain_track_gain"
	// FieldReplayGainTrackPeak holds the string denoting the replay_gain_track_peak field in the database.
	FieldReplayGainTrackPeak = "replay_gain_track_peak"
	// FieldMimeType holds the string denoting the mime_type field in the database.
	FieldMimeType = "mime_type"
	// FieldCreatedDate holds the string denoting the created_date field in the database.
	FieldCreatedDate = "created_date"
	// FieldModifiedDate holds the string denoting the modified_date field in the database.
	FieldModifiedDate = "modified_date"

	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"

	// Table holds the table name of the song in the database.
	Table = "songs"
	// TagsTable is the table the holds the tags relation/edge. The primary key declared below.
	TagsTable = "song_tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
)

// Columns holds all SQL columns for song fields.
var Columns = []string{
	FieldID,
	FieldPath,
	FieldHash,
	FieldTitle,
	FieldTitleSort,
	FieldArtists,
	FieldFirstArtist,
	FieldFirstArtistSort,
	FieldFirstAlbumArtist,
	FieldFirstAlbumArtistSort,
	FieldAlbumArtist,
	FieldAlbum,
	FieldPublisher,
	FieldFirstComposer,
	FieldComposers,
	FieldConductor,
	FieldGenre,
	FieldGrouping,
	FieldYear,
	FieldTrackNumber,
	FieldOfTrackNumber,
	FieldDiskNumber,
	FieldOfDiskNumber,
	FieldDuration,
	FieldPlayCount,
	FieldSkippedCount,
	FieldComment,
	FieldBeatsPerMinute,
	FieldCopyright,
	FieldDateTagged,
	FieldDescription,
	FieldFirstComposerSort,
	FieldArtistsSort,
	FieldLyrics,
	FieldInitialKey,
	FieldIsrc,
	FieldSubtitle,
	FieldMusicBrainzArtistID,
	FieldMusicBrainzDiscID,
	FieldMusicBrainzReleaseArtistID,
	FieldMusicBrainzReleaseCountry,
	FieldMusicBrainzReleaseGroupID,
	FieldMusicBrainzReleaseID,
	FieldMusicBrainzReleaseStatus,
	FieldMusicBrainzReleaseType,
	FieldMusicBrainzTrackID,
	FieldMusicIPID,
	FieldRemixedBy,
	FieldReplayGainAlbumGain,
	FieldReplayGainAlbumPeak,
	FieldReplayGainTrackGain,
	FieldReplayGainTrackPeak,
	FieldMimeType,
	FieldCreatedDate,
	FieldModifiedDate,
}

var (
	// TagsPrimaryKey and TagsColumn2 are the table columns denoting the
	// primary key for the tags relation (M2M).
	TagsPrimaryKey = []string{"song_id", "tag_id"}
)

var (
	// DefaultPlayCount holds the default value on creation for the play_count field.
	DefaultPlayCount uint32
	// DefaultSkippedCount holds the default value on creation for the skipped_count field.
	DefaultSkippedCount uint32
)
