// Code generated by entc, DO NOT EDIT.

package tag

const (
	// Label holds the string label denoting the tag type in the database.
	Label = "tag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeSongs holds the string denoting the songs edge name in mutations.
	EdgeSongs = "songs"

	// Table holds the table name of the tag in the database.
	Table = "tags"
	// SongsTable is the table the holds the songs relation/edge. The primary key declared below.
	SongsTable = "song_tags"
	// SongsInverseTable is the table name for the Song entity.
	// It exists in this package in order to avoid circular dependency with the "song" package.
	SongsInverseTable = "songs"
)

// Columns holds all SQL columns for tag fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// SongsPrimaryKey and SongsColumn2 are the table columns denoting the
	// primary key for the songs relation (M2M).
	SongsPrimaryKey = []string{"song_id", "tag_id"}
)
